package ir.ayeh.taamal.navigation

object Routes {
    const val Splash = "splash"
    const val Onboarding = "onboarding"
    const val Main = "main"
    const val Home = "home"
    const val Paths = "paths"
    const val PathDetail = "path/{pathId}"
    const val Challenges = "challenges"
    const val ChallengeDetail = "challenge/{challengeId}"
    const val Journal = "journal"
    const val Profile = "profile"
    const val Quran = "quran"
    const val Surah = "surah/{surahNumber}"
    const val Ayah = "ayah/{ayahId}"
    const val Search = "search"
    const val Situations = "situations"
    const val SituationDetail = "situation/{situationId}"
    const val Scenarios = "scenarios"
    const val ScenarioDetail = "scenario/{scenarioId}"
    const val Quiz = "quiz"
    const val Settings = "settings"
    const val About = "about"
    const val Help = "help"
    const val More = "more"
    const val Reports = "reports"
    const val Privacy = "privacy"
    const val Games = "games"

    fun pathDetail(id: Long) = "path/$id"
    fun challengeDetail(id: Long) = "challenge/$id"
    fun surah(number: Int) = "surah/$number"
    fun ayah(id: Long) = "ayah/$id"
    fun situation(id: Long) = "situation/$id"
    fun scenario(id: Long) = "scenario/$id"
}
